server:
    port: ${PORT:8888}

spring:
  application:\
    name: config-server\
        cloud:
        config:
            server:
                git:
                    uri: https://github.com/Marisabel176/pruebasBCK.git
                    default-label: main
                    force-pull: true
                    search-paths: config-data
